# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-06 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogo',
            name='codigo',
            field=models.CharField(max_length=3),
        ),
    ]
